services:
  api:
    build:
      context: .
    ports:
      - "4000:4000"
    command: bash -c "mix phx.server"
    volumes:
      - .:/usr/src/app:delegated
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'foodtruckpals'
      POSTGRES_PASSWORD: 'foodtruckpals'
      POSTGRES_DB: 'foodtruckpals_dev'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
